# Generated by Django 6.0.1 on 2026-01-27 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('animal_class', models.CharField(choices=[('MAMMAL', 'Mamífero'), ('BIRD', 'Ave'), ('REPTILE', 'Reptil'), ('AMPHIBIAN', 'Anfibio'), ('FISH', 'Pez'), ('INVERTEBRATE', 'Invertebrado')], db_index=True, max_length=20)),
                ('habitat', models.CharField(max_length=200)),
                ('diet', models.CharField(choices=[('CARNIVORE', 'Carnívoro'), ('HERBIVORE', 'Herbívoro'), ('OMNIVORE', 'Omnívoro'), ('INSECTIVORE', 'Insectívoro'), ('PISCIVORE', 'Piscívoro')], max_length=20)),
                ('conservation_status', models.CharField(choices=[('EXTINCT', 'Extinto'), ('EXTINCT_IN_WILD', 'Extinto en Estado Silvestre'), ('CRITICALLY_ENDANGERED', 'En Peligro Crítico'), ('ENDANGERED', 'En Peligro'), ('VULNERABLE', 'Vulnerable'), ('NEAR_THREATENED', 'Casi Amenazado'), ('LEAST_CONCERN', 'Preocupación Menor'), ('DATA_DEFICIENT', 'Datos Insuficientes'), ('NOT_EVALUATED', 'No Evaluado')], max_length=25)),
                ('fun_facts', models.JSONField(default=list)),
                ('average_lifespan', models.CharField(blank=True, max_length=50, null=True)),
                ('average_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('average_height', models.CharField(blank=True, max_length=50, null=True)),
                ('geographic_distribution', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sound_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'animals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognition_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('thumbnail_url', models.URLField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='infrastructure.animalmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='infrastructure.sessionmodel')),
            ],
            options={
                'verbose_name': 'Descubrimiento',
                'verbose_name_plural': 'Descubrimientos',
                'db_table': 'discoveries',
                'ordering': ['-discovered_at'],
            },
        ),
    ]
