# Generated by Copilot on 2026-02-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='aliases',
            field=models.JSONField(default=list, blank=True),
        ),
    ]
