# Generated by Django 5.2.11 on 2026-02-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_add_last_recognition_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='average_height',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='average_lifespan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='average_weight',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='geographic_distribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
